package com.gymtracker.app.utils

import com.gymtracker.app.data.db.entity.ExerciseEntity

object ExerciseSeed {
    val exercises = listOf(

        // ── CHEST ──────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Bench Press", muscleGroup = "Chest",
            description = "Lie flat on a bench, grip the bar slightly wider than shoulder-width. Lower the bar to your lower chest with elbows at ~75°, then press back up to full extension. Keep your feet flat, back slightly arched and shoulder blades retracted."),
        ExerciseEntity(name = "Incline Bench Press", muscleGroup = "Chest",
            description = "Set the bench to 30–45°. Grip the bar slightly wider than shoulder-width and lower it to your upper chest. Press back up. The incline angle shifts emphasis to the upper chest and front delts."),
        ExerciseEntity(name = "Decline Bench Press", muscleGroup = "Chest",
            description = "Set the bench to –15–30°. Lower the bar to your lower chest and press back up. The decline angle targets the lower chest and reduces shoulder involvement."),
        ExerciseEntity(name = "Dumbbell Bench Press", muscleGroup = "Chest",
            description = "Lie on a flat bench holding a dumbbell in each hand at chest level. Press both dumbbells up until arms are fully extended, then lower with control. Allows a greater range of motion than the barbell variation."),
        ExerciseEntity(name = "Incline Dumbbell Press", muscleGroup = "Chest",
            description = "Sit on an incline bench (30–45°) with a dumbbell in each hand. Press the dumbbells up and slightly together at the top, then lower to chest level. Targets the upper chest with a full stretch at the bottom."),
        ExerciseEntity(name = "Decline Dumbbell Press", muscleGroup = "Chest",
            description = "Lie on a decline bench and press dumbbells from chest level upward. Focuses on the lower chest. Secure your feet and keep the movement controlled throughout."),
        ExerciseEntity(name = "Dumbbell Fly", muscleGroup = "Chest",
            description = "Lie flat, hold dumbbells above chest with a slight bend in your elbows. Open your arms out in a wide arc until you feel a stretch in your chest, then bring them back together. Keep the elbow angle constant throughout."),
        ExerciseEntity(name = "Incline Dumbbell Fly", muscleGroup = "Chest",
            description = "Same as the dumbbell fly but performed on an incline bench. The incline shifts the stretch and emphasis to the upper chest. Lower until elbows are at shoulder level, then squeeze back together."),
        ExerciseEntity(name = "Push-Up", muscleGroup = "Chest",
            description = "Start in a plank with hands slightly wider than shoulder-width. Lower your chest to the floor by bending your elbows at ~45°, then push back up. Keep your core tight and body in a straight line throughout."),
        ExerciseEntity(name = "Decline Push-Up", muscleGroup = "Chest",
            description = "Elevate your feet on a bench or box and perform a standard push-up. The decline angle increases upper chest and front delt activation. The higher the feet, the more upper-chest emphasis."),
        ExerciseEntity(name = "Chest Dip", muscleGroup = "Chest",
            description = "On parallel bars, lean your torso forward at ~30° as you dip. Lower until your upper arms are parallel to the floor, then push back up. Leaning forward shifts the work from triceps to the lower chest."),
        ExerciseEntity(name = "Cable Crossover (High to Low)", muscleGroup = "Chest",
            description = "Set cables at the highest pulley position. Grab a handle in each hand, step forward and pull both handles down and across your body, crossing them in front of your hips. Squeeze your chest at the bottom."),
        ExerciseEntity(name = "Cable Crossover (Low to High)", muscleGroup = "Chest",
            description = "Set cables at the lowest pulley position. Pull both handles up and across your body, crossing them in front of your upper chest. Focuses on the upper chest with constant tension throughout."),
        ExerciseEntity(name = "Cable Fly", muscleGroup = "Chest",
            description = "Set cables at mid-chest height. Grab a handle in each hand, step forward and pull both handles together in a wide arc in front of your chest. Squeeze hard at the point of contact."),
        ExerciseEntity(name = "Pec Deck Machine", muscleGroup = "Chest",
            description = "Sit with your back flat against the pad and place your arms on the machine's pads. Press both pads together in front of your chest, hold the contraction briefly, then return with control. Isolates the chest without loading the shoulder joint."),
        ExerciseEntity(name = "Machine Chest Press", muscleGroup = "Chest",
            description = "Sit with your back against the pad, grip the handles at chest level and press forward until arms are fully extended. Return with control. The fixed path makes it ideal for beginners or for pre-fatiguing the chest."),
        ExerciseEntity(name = "Svend Press", muscleGroup = "Chest",
            description = "Hold two weight plates pressed together between your palms at chest level. Press them straight out in front of you while actively squeezing them together, then pull back. The constant inward force creates intense chest contraction."),

        // ── BACK ───────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Pull-Up", muscleGroup = "Back",
            description = "Hang from a bar with an overhand grip slightly wider than shoulder-width. Pull your chest up toward the bar by driving your elbows down and back. Lower with full control. Targets the lats, traps and biceps."),
        ExerciseEntity(name = "Chin-Up", muscleGroup = "Back",
            description = "Hang from a bar with an underhand (supinated) grip, hands shoulder-width apart. Pull your chin above the bar, then lower slowly. The underhand grip increases bicep involvement compared to a standard pull-up."),
        ExerciseEntity(name = "Wide-Grip Pull-Up", muscleGroup = "Back",
            description = "Grip the bar much wider than shoulder-width with an overhand grip. Pull your upper chest toward the bar. The wide grip limits range of motion but increases lat width emphasis."),
        ExerciseEntity(name = "Inverted Row", muscleGroup = "Back",
            description = "Lie under a bar set at waist height, grip it overhand and hang with straight arms. Keep your body rigid and pull your chest up to the bar. A great bodyweight horizontal rowing movement for mid-back."),
        ExerciseEntity(name = "Barbell Row", muscleGroup = "Back",
            description = "Hinge at the hips with a flat back (torso ~45°), grip the bar overhand. Pull the bar to your lower abs by driving your elbows back. Lower with control. One of the best mass builders for the entire back."),
        ExerciseEntity(name = "Barbell Row (Underhand)", muscleGroup = "Back",
            description = "Same setup as the barbell row but with an underhand (supinated) grip. This grip allows you to keep elbows closer to your body, increasing lower lat and bicep activation."),
        ExerciseEntity(name = "Pendlay Row", muscleGroup = "Back",
            description = "Set up like a barbell row but with the bar resting on the floor each rep. Pull explosively from a dead stop to your lower chest, then lower the bar fully back down. Builds power and strength in the upper back."),
        ExerciseEntity(name = "T-Bar Row", muscleGroup = "Back",
            description = "Load one end of a barbell into a T-bar handle or corner. Straddle the bar, hinge forward, grip the handle and row it up toward your chest. Allows heavy loading with a neutral hand position."),
        ExerciseEntity(name = "T-Bar Row (Close Grip)", muscleGroup = "Back",
            description = "Same as T-Bar Row but using a close V-handle. The closer grip allows a greater range of motion and more lower lat stretch at the bottom of the movement."),
        ExerciseEntity(name = "Dumbbell Row", muscleGroup = "Back",
            description = "Place one knee and hand on a bench for support, hold a dumbbell in the other hand. Pull the dumbbell straight up to your hip, keeping your elbow close. Lower slowly. Great for unilateral lat and rhomboid development."),
        ExerciseEntity(name = "Kroc Row", muscleGroup = "Back",
            description = "A heavy, high-rep version of the dumbbell row with some controlled momentum. Use a heavier weight than a strict row allows, driving the dumbbell explosively upward and letting your torso rotate slightly."),
        ExerciseEntity(name = "Meadows Row", muscleGroup = "Back",
            description = "Stand perpendicular to a landmine, foot closest to the bar in a staggered stance. Grip the sleeve end and row it upward, letting your elbow flare out. Creates a unique angle that targets the outer lat and teres major."),
        ExerciseEntity(name = "Chest-Supported Row (Dumbbell)", muscleGroup = "Back",
            description = "Lie face-down on an incline bench set to ~30–45°. Hold a dumbbell in each hand and row them up toward your hips. The chest support eliminates momentum and lower back strain, isolating the back."),
        ExerciseEntity(name = "Chest-Supported Row (Barbell)", muscleGroup = "Back",
            description = "Lie chest-down on a high incline bench with a barbell hanging below. Row the bar up to the bench. Like the dumbbell version, this removes momentum and focuses entirely on the middle back and lats."),
        ExerciseEntity(name = "Lat Pulldown (Wide Grip)", muscleGroup = "Back",
            description = "Sit at a cable machine, grip the bar wider than shoulder-width with an overhand grip. Pull the bar down to your upper chest by driving your elbows toward your hips. Lean back slightly and squeeze at the bottom."),
        ExerciseEntity(name = "Lat Pulldown (Close Grip)", muscleGroup = "Back",
            description = "Use a close or parallel grip handle. Pull it down to your chin, keeping your elbows pointing straight down. The closer grip allows a greater range of motion and a deeper stretch at the top."),
        ExerciseEntity(name = "Lat Pulldown (Reverse Grip)", muscleGroup = "Back",
            description = "Grip the bar underhand (supinated) at shoulder-width. Pull it to your upper chest. The reverse grip recruits more biceps and allows the elbows to travel further behind the body at the bottom."),
        ExerciseEntity(name = "Seated Cable Row (Wide Grip)", muscleGroup = "Back",
            description = "Sit upright, grip a wide bar attached to a low cable and row it to your abdomen. Keep your torso still and shoulders back. The wide grip targets the upper back and rear delts more than the narrow version."),
        ExerciseEntity(name = "Seated Cable Row (Close Grip)", muscleGroup = "Back",
            description = "Sit upright, grip a V-bar (close neutral grip) and pull it to your belly button. Drive your elbows back and squeeze your shoulder blades together at the end. Targets the middle back and lats."),
        ExerciseEntity(name = "Standing Cable Row (High)", muscleGroup = "Back",
            description = "Set the pulley at face height. Pull a rope attachment toward your face with elbows high and wide, finishing with your hands by your ears. Targets the rear delts, upper traps and external rotators."),
        ExerciseEntity(name = "Single-Arm Cable Row", muscleGroup = "Back",
            description = "Stand or sit sideways to a cable, grip a single handle and row it toward your hip. Allows full rotation of the torso for a deeper stretch and greater range of motion. Great for fixing imbalances between sides."),
        ExerciseEntity(name = "Straight-Arm Pulldown", muscleGroup = "Back",
            description = "Stand in front of a high cable with arms extended. Without bending your elbows, pull the bar or rope down in an arc until it touches your thighs. This isolates the lats and removes the biceps from the movement."),
        ExerciseEntity(name = "Cable Pull-Through", muscleGroup = "Back",
            description = "Stand facing away from a low cable, reach through your legs to grab the rope. Hinge forward at the hips with a flat back, then drive your hips forward to stand up. Targets the glutes and hamstrings with back extension."),
        ExerciseEntity(name = "Deadlift", muscleGroup = "Back",
            description = "Stand over the bar with feet hip-width apart. Hinge at the hips, grip the bar just outside your legs, brace your core and drive the floor away to stand up. Arguably the greatest full-body strength exercise."),
        ExerciseEntity(name = "Sumo Deadlift", muscleGroup = "Back",
            description = "Stand with a wide stance (toes pointing out), grip the bar inside your legs. The wider stance reduces the range of motion and shifts emphasis toward the hips and inner thighs compared to conventional."),
        ExerciseEntity(name = "Romanian Deadlift", muscleGroup = "Back",
            description = "Start standing, hold the bar at hip level. Hinge at the hips while keeping a slight knee bend, lowering the bar along your legs until you feel a deep hamstring stretch. Drive your hips forward to return."),
        ExerciseEntity(name = "Hyperextension", muscleGroup = "Back",
            description = "Lie face-down on a hyperextension bench with your hips at the pad's edge. Lower your torso toward the floor, then raise it back up until your body forms a straight line. Targets the erector spinae and glutes."),
        ExerciseEntity(name = "Machine Row", muscleGroup = "Back",
            description = "Sit at the rowing machine with your chest on the pad. Grip the handles and pull them toward your body, squeezing your shoulder blades together. A great controlled option that eliminates lower back involvement."),

        // ── SHOULDERS ──────────────────────────────────────────────────────────
        ExerciseEntity(name = "Overhead Press (Barbell)", muscleGroup = "Shoulders",
            description = "Stand (or sit) with the bar at your upper chest, hands just outside shoulder-width. Press the bar straight overhead until your arms lock out, moving your head back to allow the bar to travel vertically. Lower with control."),
        ExerciseEntity(name = "Overhead Press (Dumbbell)", muscleGroup = "Shoulders",
            description = "Hold a dumbbell in each hand at shoulder height, palms facing forward. Press both dumbbells overhead until arms are fully extended, then lower back to shoulder level. Allows a natural wrist angle and independent arm movement."),
        ExerciseEntity(name = "Arnold Press", muscleGroup = "Shoulders",
            description = "Start with dumbbells at chin height, palms facing you. As you press upward, rotate your palms outward so they face forward at the top. This rotation works all three delt heads through the full range."),
        ExerciseEntity(name = "Machine Shoulder Press", muscleGroup = "Shoulders",
            description = "Sit in the machine with the handles at shoulder level. Press upward until arms are extended, then lower with control. The fixed path makes it safer for beginners and allows you to focus purely on the delts."),
        ExerciseEntity(name = "Lateral Raise (Dumbbell)", muscleGroup = "Shoulders",
            description = "Stand holding dumbbells at your sides, slight bend in elbows. Raise both arms out to the sides until they reach shoulder height, then lower slowly. Lead with your elbows and avoid shrugging to isolate the side delts."),
        ExerciseEntity(name = "Lateral Raise (Cable)", muscleGroup = "Shoulders",
            description = "Stand beside a low cable with the handle in the far hand. Raise your arm out to the side to shoulder height. The cable provides tension at the bottom of the movement that dumbbells lack."),
        ExerciseEntity(name = "Lateral Raise (Machine)", muscleGroup = "Shoulders",
            description = "Sit in the machine and push the pads upward with your elbows until your arms reach shoulder height. The machine provides consistent resistance and removes stabilisation demands."),
        ExerciseEntity(name = "Front Raise (Barbell)", muscleGroup = "Shoulders",
            description = "Stand holding a barbell with an overhand grip at hip level. Raise it straight in front of you to shoulder height, then lower with control. Targets the anterior (front) deltoid."),
        ExerciseEntity(name = "Front Raise (Dumbbell)", muscleGroup = "Shoulders",
            description = "Hold a dumbbell in each hand at your sides. Raise one or both forward to shoulder height, keeping a slight bend in the elbow. Targets the front delt. Avoid using momentum from your torso."),
        ExerciseEntity(name = "Front Raise (Cable)", muscleGroup = "Shoulders",
            description = "Stand in front of a low cable with the handle in one or both hands. Raise the handle forward to shoulder height. The cable keeps the tension constant throughout, unlike dumbbells."),
        ExerciseEntity(name = "Rear Delt Fly (Dumbbell)", muscleGroup = "Shoulders",
            description = "Bend forward at the hips with a flat back (or sit on the edge of a bench). Hold dumbbells below your chest and raise them out to the sides in a reverse-fly motion. Targets the often-neglected rear deltoid."),
        ExerciseEntity(name = "Rear Delt Fly (Cable)", muscleGroup = "Shoulders",
            description = "Set cables at head height and cross your arms to grab the opposite handle. Pull each handle out to the side in a reverse-fly motion. The cables provide constant tension throughout the range."),
        ExerciseEntity(name = "Rear Delt Machine", muscleGroup = "Shoulders",
            description = "Sit facing the pec-deck machine and grip the handles behind the pads. Push the handles backward and outward in a wide arc. A simple, isolated movement for the rear delts without the balance demands of free weights."),
        ExerciseEntity(name = "Face Pull", muscleGroup = "Shoulders",
            description = "Set a rope on a high cable. Pull the rope toward your face with elbows high and flared out wide, separating the handles as they reach your ears. Excellent for rear delts, external rotation and shoulder health."),
        ExerciseEntity(name = "Upright Row (Barbell)", muscleGroup = "Shoulders",
            description = "Grip a barbell with hands shoulder-width apart. Pull it straight up along your body to chin height, leading with your elbows. Targets the side delts and traps. Avoid a very narrow grip which can stress the shoulder joint."),
        ExerciseEntity(name = "Upright Row (Cable)", muscleGroup = "Shoulders",
            description = "Attach a straight bar or rope to a low cable. Perform the same upright rowing motion as with a barbell. The cable provides constant tension, particularly useful at the bottom range."),

        // ── BICEPS ─────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Barbell Curl", muscleGroup = "Biceps",
            description = "Stand holding a barbell with an underhand grip, hands shoulder-width apart. Curl the bar from your hips to your chin by flexing your elbows, keeping them pinned at your sides. Lower with control."),
        ExerciseEntity(name = "EZ-Bar Curl", muscleGroup = "Biceps",
            description = "Same as the barbell curl but using an EZ (angled) bar. The angled grip is easier on the wrists and forearms, making it a more comfortable option for heavy curls."),
        ExerciseEntity(name = "Dumbbell Curl", muscleGroup = "Biceps",
            description = "Stand holding a dumbbell in each hand, palms facing forward. Curl one or both up toward your shoulders, supinating (rotating) the wrist at the top for a peak contraction. Keep elbows still."),
        ExerciseEntity(name = "Hammer Curl", muscleGroup = "Biceps",
            description = "Hold dumbbells at your sides with a neutral (thumbs-up) grip. Curl them upward without rotating your wrists. This grip targets the brachialis and brachioradialis in addition to the biceps."),
        ExerciseEntity(name = "Incline Dumbbell Curl", muscleGroup = "Biceps",
            description = "Sit on an incline bench (45–60°), letting the dumbbells hang at arm's length. Curl them up from this stretched position. The incline provides a longer range of motion and a greater stretch on the long head."),
        ExerciseEntity(name = "Concentration Curl", muscleGroup = "Biceps",
            description = "Sit on a bench, rest your elbow on your inner thigh. Curl the dumbbell straight up toward your shoulder, squeezing hard at the top. Eliminating momentum makes this a highly isolated bicep movement."),
        ExerciseEntity(name = "Preacher Curl (Barbell)", muscleGroup = "Biceps",
            description = "Rest your upper arms on the preacher bench pad, grip a barbell underhand. Curl the bar up toward your chin, then lower slowly until arms are almost fully extended. The pad prevents cheating with the elbows."),
        ExerciseEntity(name = "Preacher Curl (Dumbbell)", muscleGroup = "Biceps",
            description = "Same as the barbell preacher curl but performed one arm at a time with a dumbbell. Allows full supination at the top for a stronger peak contraction."),
        ExerciseEntity(name = "Cable Curl (Bar)", muscleGroup = "Biceps",
            description = "Attach a straight bar to a low cable. Stand back slightly and curl the bar toward your chin. The cable provides constant tension through the full range of motion, unlike free weights where tension drops at the top."),
        ExerciseEntity(name = "Cable Curl (Rope)", muscleGroup = "Biceps",
            description = "Attach a rope to a low cable. Curl it up while spreading the ends apart at the top for an intensified peak contraction. The rope allows a more natural wrist rotation throughout the movement."),
        ExerciseEntity(name = "Cable Hammer Curl", muscleGroup = "Biceps",
            description = "Attach a rope to a low cable and grip it with a neutral (hammer) grip. Curl the rope toward your shoulders without rotating your wrists. Targets the brachialis with constant cable tension."),
        ExerciseEntity(name = "Reverse Curl", muscleGroup = "Biceps",
            description = "Hold a barbell or dumbbells with an overhand (pronated) grip. Curl the weight up toward your chest. The reversed grip shifts focus to the brachialis, brachioradialis and wrist extensors."),
        ExerciseEntity(name = "Spider Curl", muscleGroup = "Biceps",
            description = "Lie face-down on an incline bench (~45°), let the dumbbells hang straight below you. Curl them up toward your shoulders. This position keeps the elbows ahead of the body, emphasising the short (inner) head of the bicep."),

        // ── TRICEPS ────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Tricep Dip", muscleGroup = "Triceps",
            description = "On parallel bars, keep your torso upright and elbows pointing back. Lower until your upper arms are parallel to the floor, then push back up. Staying vertical emphasises the triceps; leaning forward shifts work to the chest."),
        ExerciseEntity(name = "Close-Grip Bench Press", muscleGroup = "Triceps",
            description = "Lie on a flat bench, grip the bar with hands shoulder-width (or slightly closer). Lower the bar to your lower chest with elbows tucked close to your body. Press back up. One of the best mass builders for the triceps."),
        ExerciseEntity(name = "Skull Crusher (Barbell)", muscleGroup = "Triceps",
            description = "Lie on a bench with a barbell held straight above your chest. Bend your elbows to lower the bar toward your forehead (keeping upper arms still), then extend back up. Primarily targets the long head of the triceps."),
        ExerciseEntity(name = "Skull Crusher (EZ-Bar)", muscleGroup = "Triceps",
            description = "Same movement as the barbell skull crusher but using an EZ-bar. The angled grip reduces wrist and elbow strain, making it a more comfortable heavy triceps exercise."),
        ExerciseEntity(name = "Overhead Tricep Extension (Dumbbell)", muscleGroup = "Triceps",
            description = "Hold a dumbbell overhead with both hands (or one hand). Lower it behind your head by bending at the elbows, keeping upper arms vertical. Extend back up. Excellent stretch on the long head of the triceps."),
        ExerciseEntity(name = "Overhead Tricep Extension (Barbell)", muscleGroup = "Triceps",
            description = "Hold a barbell (or EZ-bar) overhead with a narrow grip. Lower it behind your head by bending at the elbows, keeping your upper arms pointed straight up. Press back to the start."),
        ExerciseEntity(name = "Tricep Pushdown (Bar)", muscleGroup = "Triceps",
            description = "Attach a straight bar to a high cable. Stand close, grip the bar overhand and push it downward until your arms are fully extended. Keep your elbows pinned at your sides. Squeeze at full extension."),
        ExerciseEntity(name = "Tricep Pushdown (Rope)", muscleGroup = "Triceps",
            description = "Attach a rope to a high cable. Grip each end and push down while spreading the rope apart at the bottom for a stronger contraction. The rope allows the natural rotation of the wrists."),
        ExerciseEntity(name = "Overhead Tricep Extension (Cable)", muscleGroup = "Triceps",
            description = "Face away from a high cable with the rope behind your head. Extend your arms forward and downward until straight. Facing away from the cable keeps constant tension at the stretched position."),
        ExerciseEntity(name = "Tricep Kickback (Dumbbell)", muscleGroup = "Triceps",
            description = "Hinge forward at the hips, upper arm parallel to the floor. Hold a dumbbell and extend your elbow until your arm is straight, then lower back. Fully extending the elbow at the top is key to maximum tricep contraction."),
        ExerciseEntity(name = "Tricep Kickback (Cable)", muscleGroup = "Triceps",
            description = "Same motion as the dumbbell kickback but with a low cable. The cable provides tension at the bottom stretched position where dumbbells offer none."),
        ExerciseEntity(name = "Diamond Push-Up", muscleGroup = "Triceps",
            description = "Place your hands together under your chest, forming a diamond shape. Perform a push-up while keeping your elbows close to your body. The narrow hand position maximises tricep involvement."),
        ExerciseEntity(name = "Machine Tricep Extension", muscleGroup = "Triceps",
            description = "Sit in the machine and grip the handles above your head. Press them downward by extending your elbows. The machine isolates the triceps with a stable, fixed plane of motion."),

        // ── LEGS ───────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Squat (Barbell)", muscleGroup = "Legs",
            description = "Place the bar on your upper traps, feet shoulder-width apart and toes slightly out. Brace your core and sit straight down, keeping your chest up and knees tracking over your toes. Stand back up by driving through your heels."),
        ExerciseEntity(name = "Front Squat", muscleGroup = "Legs",
            description = "Rest the bar on your front delts with elbows high and pointing forward. Squat down with an upright torso and knees tracking forward. The front rack position requires more quad dominance and core stability than a back squat."),
        ExerciseEntity(name = "Goblet Squat", muscleGroup = "Legs",
            description = "Hold a dumbbell or kettlebell vertically at your chest. Squat down while keeping the weight close to your body and chest upright. A great technique builder that naturally encourages an upright torso."),
        ExerciseEntity(name = "Hack Squat", muscleGroup = "Legs",
            description = "Load the hack squat machine and stand on the platform with feet hip-width apart. Lower the sled until your knees are at 90° or deeper, then push back up. Allows deep squatting with reduced spinal loading."),
        ExerciseEntity(name = "Sumo Squat", muscleGroup = "Legs",
            description = "Stand with a very wide stance, toes turned out significantly. Hold a dumbbell or barbell and squat down, keeping your torso upright. The wide stance increases the load on the inner thighs (adductors) and glutes."),
        ExerciseEntity(name = "Leg Press", muscleGroup = "Legs",
            description = "Sit in the leg press machine, place feet hip-width on the platform. Lower the platform toward your chest until your knees reach 90°, then push back up. Foot placement height shifts emphasis between quads (low) and glutes/hamstrings (high)."),
        ExerciseEntity(name = "Bulgarian Split Squat", muscleGroup = "Legs",
            description = "Stand about 2 feet in front of a bench, place one foot behind you on it. Lower your rear knee toward the floor by bending your front leg, then drive back up. A demanding unilateral exercise for quads and glutes."),
        ExerciseEntity(name = "Lunges (Barbell)", muscleGroup = "Legs",
            description = "With a barbell on your traps, step one foot forward and lower your rear knee to just above the floor. Push through the front foot to return to start. Trains quads, glutes and hip stability together."),
        ExerciseEntity(name = "Lunges (Dumbbell)", muscleGroup = "Legs",
            description = "Hold a dumbbell in each hand. Step forward with one foot, lower the rear knee to the floor, then return. The dumbbells at your sides lower your centre of gravity for easier balance."),
        ExerciseEntity(name = "Walking Lunges", muscleGroup = "Legs",
            description = "Perform lunges continuously forward, stepping the rear foot to meet the front and then lunging forward again. A dynamic variation that also trains coordination, hip flexors and cardiovascular fitness."),
        ExerciseEntity(name = "Step-Up", muscleGroup = "Legs",
            description = "Stand in front of a box or bench. Step one foot up onto it, drive through that heel to bring your body up until your leg is straight, then step back down. Targets quads and glutes with a strong unilateral emphasis."),
        ExerciseEntity(name = "Leg Extension", muscleGroup = "Legs",
            description = "Sit in the machine with the pad on your lower shins. Extend your legs to fully straighten the knees, pause and lower with control. Isolates the quadriceps; avoid locking out aggressively if you have knee issues."),
        ExerciseEntity(name = "Leg Curl (Lying)", muscleGroup = "Legs",
            description = "Lie face-down on the machine with the pad behind your ankles. Curl your heels toward your glutes, pause at peak contraction, then lower slowly. Isolates the hamstrings with minimal glute involvement."),
        ExerciseEntity(name = "Leg Curl (Seated)", muscleGroup = "Legs",
            description = "Sit upright in the machine and place the pad on your shins. Curl your legs downward toward the floor. The seated position places the hamstrings in a stretched starting position for potentially greater activation."),
        ExerciseEntity(name = "Nordic Curl", muscleGroup = "Legs",
            description = "Kneel with your ankles secured. Slowly lower your torso toward the floor by extending your knees, resisting the descent with your hamstrings. Return by pushing yourself back up. An advanced eccentric hamstring exercise."),
        ExerciseEntity(name = "Romanian Deadlift (Dumbbell)", muscleGroup = "Legs",
            description = "Hold a dumbbell in each hand at your sides. Hinge at the hips with a slight knee bend, lowering the dumbbells along your legs until you feel a hamstring stretch. Drive your hips forward to stand up."),
        ExerciseEntity(name = "Cable Pull-Through (Legs)", muscleGroup = "Legs",
            description = "Face away from a low cable with the rope between your legs. Hinge forward at the hips with a flat back and a soft knee bend, then drive your hips forward to stand up. A hip-hinge exercise targeting glutes and hamstrings."),

        // ── GLUTES ─────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Hip Thrust (Barbell)", muscleGroup = "Glutes",
            description = "Sit with your upper back on a bench, barbell over your hips. Drive your hips up by squeezing your glutes until your thighs are parallel to the floor. Hold the top position briefly for maximum contraction. The premier glute-building exercise."),
        ExerciseEntity(name = "Hip Thrust (Machine)", muscleGroup = "Glutes",
            description = "Use a dedicated hip thrust machine. Place your back against the pad and drive the platform upward with your hips. The machine allows easier loading and a more consistent position than the bench version."),
        ExerciseEntity(name = "Glute Bridge", muscleGroup = "Glutes",
            description = "Lie on your back with knees bent, feet flat on the floor. Drive your hips up by squeezing your glutes until your body forms a straight line from knees to shoulders. A beginner-friendly glute activation exercise."),
        ExerciseEntity(name = "Cable Kickback", muscleGroup = "Glutes",
            description = "Attach a cable cuff to your ankle and stand facing the machine. Keeping your leg straight, kick it back and up, squeezing your glute at the top. Lower with control. Isolates the glute with constant cable tension."),
        ExerciseEntity(name = "Donkey Kick", muscleGroup = "Glutes",
            description = "Start on all fours (hands and knees). Keeping your knee bent at 90°, drive one heel toward the ceiling by squeezing your glute. Lower back down without touching the floor. Can be loaded with a cable cuff or resistance band."),
        ExerciseEntity(name = "Hip Abduction (Machine)", muscleGroup = "Glutes",
            description = "Sit in the abduction machine with the pads on the outside of your knees. Push your knees outward against the resistance, squeezing your glutes and abductors at the end range. Return slowly."),
        ExerciseEntity(name = "Hip Adduction (Machine)", muscleGroup = "Glutes",
            description = "Sit in the adduction machine with the pads on the inside of your knees. Squeeze your thighs together against the resistance. Targets the inner thigh muscles (adductors). Use a full range of motion."),
        ExerciseEntity(name = "Cable Hip Abduction", muscleGroup = "Glutes",
            description = "Attach a cable cuff to your ankle. Stand sideways to the machine and raise the cuffed leg out to the side against the cable resistance. Targets the glute medius and hip abductors. Keep your torso upright."),
        ExerciseEntity(name = "Single-Leg Romanian Deadlift", muscleGroup = "Glutes",
            description = "Balance on one foot holding a dumbbell (or barbell). Hinge forward at the hip, lowering the weight while extending the free leg behind you. Return to upright. Challenges glutes, hamstrings and hip stability simultaneously."),

        // ── CALVES ─────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Standing Calf Raise", muscleGroup = "Calves",
            description = "Stand on the edge of a step or calf raise machine with heels hanging off. Rise up onto your toes as high as possible, hold briefly, then lower as far as you can for a full stretch. Targets the gastrocnemius (upper calf)."),
        ExerciseEntity(name = "Seated Calf Raise", muscleGroup = "Calves",
            description = "Sit in the calf raise machine with your knees bent at 90° and the pad on your thighs. Raise your heels as high as possible, hold, then lower for a stretch. The bent knee position shifts emphasis to the soleus (deeper calf muscle)."),
        ExerciseEntity(name = "Donkey Calf Raise", muscleGroup = "Calves",
            description = "Hinge forward and rest your torso on a bench or bar. Raise and lower your heels through a full range of motion. The forward lean changes the force angle and reportedly provides a superior stretch on the gastrocnemius."),
        ExerciseEntity(name = "Leg Press Calf Raise", muscleGroup = "Calves",
            description = "On the leg press machine, place only the balls of your feet on the lower edge of the platform. Push through your toes by plantar-flexing your ankles. An easy way to load the calves heavily with controlled range."),
        ExerciseEntity(name = "Single-Leg Calf Raise", muscleGroup = "Calves",
            description = "Stand on one foot on the edge of a step. Perform a full calf raise, rising onto your toes and then lowering your heel fully below the step level. Doubles the load on each calf compared to bilateral raises."),

        // ── CORE ───────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Plank", muscleGroup = "Core",
            description = "Support your body on your forearms and toes with a straight body line from head to heels. Brace your core, squeeze your glutes and hold the position. Avoid letting your hips sag or rise up."),
        ExerciseEntity(name = "Side Plank", muscleGroup = "Core",
            description = "Lie on your side and raise your body on one forearm and the side of your foot. Keep your body rigid in a straight line. Targets the obliques and lateral core stabilisers. Hold for time or add hip dips for reps."),
        ExerciseEntity(name = "Crunch", muscleGroup = "Core",
            description = "Lie on your back with knees bent, hands behind your head or across your chest. Curl your upper back off the floor by contracting your abs, then lower back down. Keep your lower back in contact with the floor."),
        ExerciseEntity(name = "Bicycle Crunch", muscleGroup = "Core",
            description = "Lie on your back with hands behind your head. Simultaneously rotate your right elbow toward your left knee while extending the right leg. Alternate sides in a cycling motion. One of the most effective oblique exercises."),
        ExerciseEntity(name = "Sit-Up", muscleGroup = "Core",
            description = "Lie on your back with knees bent, cross your arms over your chest. Use your abs to raise your entire torso to an upright seated position, then lower with control. Greater range of motion than a crunch, involving the hip flexors more."),
        ExerciseEntity(name = "V-Up", muscleGroup = "Core",
            description = "Lie flat, arms overhead. Simultaneously raise your straight legs and reach your hands toward your feet, forming a 'V' shape. Lower both simultaneously. A challenging movement requiring coordination and significant core strength."),
        ExerciseEntity(name = "Russian Twist", muscleGroup = "Core",
            description = "Sit with your knees bent and torso leaning back at 45°. Hold a weight or keep hands together and rotate your torso from side to side, touching the weight to the floor beside each hip. Targets the obliques heavily."),
        ExerciseEntity(name = "Leg Raise (Hanging)", muscleGroup = "Core",
            description = "Hang from a pull-up bar with straight arms. Raise your straight legs to horizontal (or higher) by flexing at the hips. Lower with control. An advanced exercise targeting the lower abdominals and hip flexors."),
        ExerciseEntity(name = "Leg Raise (Lying)", muscleGroup = "Core",
            description = "Lie flat on your back with legs extended. Keeping legs straight, raise them to 90° (or until your lower back begins to lift), then lower slowly without fully resting them on the floor. Targets the lower abs."),
        ExerciseEntity(name = "Knee Raise (Hanging)", muscleGroup = "Core",
            description = "Hang from a bar and bring your knees up toward your chest by flexing at the hips. Lower them back down with control. Easier than straight-leg raises but still effective for lower abs and hip flexors."),
        ExerciseEntity(name = "Ab Wheel Rollout", muscleGroup = "Core",
            description = "Kneel behind an ab wheel. Roll it forward until your body is nearly parallel to the floor, then pull it back using your core. One of the most demanding anti-extension core exercises, also loading the lats."),
        ExerciseEntity(name = "Cable Crunch", muscleGroup = "Core",
            description = "Kneel in front of a high cable with a rope attachment held behind your head. Crunch your torso downward toward the floor by rounding your spine. The cable allows you to load the abs more heavily than bodyweight exercises."),
        ExerciseEntity(name = "Cable Woodchop (High to Low)", muscleGroup = "Core",
            description = "Set the cable high. With straight arms, pull it diagonally downward and across your body toward the opposite hip in a chopping motion. Rotate from the hips. Trains rotational power and the obliques."),
        ExerciseEntity(name = "Cable Woodchop (Low to High)", muscleGroup = "Core",
            description = "Set the cable low. Pull it diagonally upward across your body toward the opposite shoulder. The upward path is excellent for the obliques and core rotation from a different angle."),
        ExerciseEntity(name = "Dragon Flag", muscleGroup = "Core",
            description = "Lie on a bench, grip it behind your head. Raise your rigid body off the bench, balancing only on your shoulder blades. Lower your body toward the bench without touching it. An extremely advanced core movement made famous by Bruce Lee."),
        ExerciseEntity(name = "Dead Bug", muscleGroup = "Core",
            description = "Lie on your back, arms extended toward the ceiling, hips and knees at 90°. Slowly lower one arm overhead while extending the opposite leg, keeping your lower back pressed to the floor. Return and repeat on the other side."),
        ExerciseEntity(name = "Hollow Hold", muscleGroup = "Core",
            description = "Lie on your back and press your lower back firmly into the floor. Raise your arms overhead, legs, head and shoulders slightly off the floor. Hold this 'banana' shape. A foundational gymnastics core exercise for tension and control."),
        ExerciseEntity(name = "Pallof Press", muscleGroup = "Core",
            description = "Stand sideways to a cable machine, hold the handle at your chest with both hands. Press it straight out in front of you and hold, then return to your chest. The cable tries to rotate your torso — you resist it, training anti-rotation stability."),

        // ── TRAPS ──────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Barbell Shrug", muscleGroup = "Traps",
            description = "Stand holding a barbell with an overhand grip at hip level. Elevate your shoulders straight up toward your ears as high as possible, hold briefly, then lower under control. Keep your arms straight throughout."),
        ExerciseEntity(name = "Dumbbell Shrug", muscleGroup = "Traps",
            description = "Hold a dumbbell in each hand at your sides. Shrug your shoulders straight up toward your ears, pause at the top, then lower. The dumbbells allow slightly more range of motion than a barbell."),
        ExerciseEntity(name = "Cable Shrug", muscleGroup = "Traps",
            description = "Stand between two low cables or in front of one. Hold the bar or handles and shrug straight up. The cable provides constant tension through the full range, unlike free weights where tension drops at the bottom."),
        ExerciseEntity(name = "Farmer's Walk", muscleGroup = "Traps",
            description = "Pick up a heavy dumbbell or kettlebell in each hand. Walk forward for a set distance or time with an upright posture. Trains grip strength, traps and total body stability under continuous load."),

        // ── FOREARMS ───────────────────────────────────────────────────────────
        ExerciseEntity(name = "Wrist Curl", muscleGroup = "Forearms",
            description = "Sit on a bench and rest your forearms on your thighs with your palms facing up, holding a barbell or dumbbells. Curl your wrists upward as far as possible, then lower fully. Targets the wrist flexors."),
        ExerciseEntity(name = "Reverse Wrist Curl", muscleGroup = "Forearms",
            description = "Rest your forearms on your thighs with palms facing down. Curl your wrists upward against the resistance. Targets the wrist extensors on the top of the forearm, which are often neglected."),
        ExerciseEntity(name = "Wrist Roller", muscleGroup = "Forearms",
            description = "Hold a wrist roller (handle with a rope and weight attached) at arm's length. Alternately rotate each wrist to wind the rope up, raising the weight. Then slowly reverse. An exhausting exercise for the entire forearm."),
        ExerciseEntity(name = "Behind-the-Back Wrist Curl", muscleGroup = "Forearms",
            description = "Hold a barbell behind your back with an underhand grip. Let the bar roll down to your fingertips, then curl it back up into your palm by flexing your wrists. Allows a greater range of motion than the standard wrist curl."),

        // ── CARDIO ─────────────────────────────────────────────────────────────
        ExerciseEntity(name = "Running (Treadmill)", muscleGroup = "Cardio",
            description = "Run or walk at a set pace and incline on the treadmill. Adjust speed and gradient to vary intensity. Can be used for steady-state cardio or HIIT intervals. Track time, distance or calories."),
        ExerciseEntity(name = "Cycling (Stationary Bike)", muscleGroup = "Cardio",
            description = "Pedal on a stationary bike at a chosen resistance and cadence. Low-impact on the joints compared to running. Useful for warm-up, active recovery or longer cardio sessions."),
        ExerciseEntity(name = "Jump Rope", muscleGroup = "Cardio",
            description = "Skip over a rope at your chosen pace. An efficient full-body cardio exercise that also improves coordination, rhythm and calves. Use double-unders or varied footwork patterns to increase intensity."),
        ExerciseEntity(name = "Rowing Machine", muscleGroup = "Cardio",
            description = "Sit in the rowing machine, grip the handle and push through your legs while pulling the handle to your lower chest. A full-body cardio and strength exercise engaging legs, back and arms. Maintain a strong upright finish position."),
        ExerciseEntity(name = "Elliptical", muscleGroup = "Cardio",
            description = "Stand on the elliptical and push through a smooth, oval pedalling motion. A very low-impact option that still provides a full-body cardiovascular workout. Use the handles to add upper-body involvement."),
        ExerciseEntity(name = "Stair Climber", muscleGroup = "Cardio",
            description = "Step onto the machine and climb a continuous flight of stairs. A high-intensity cardio exercise that also loads the quads, glutes and calves. Keep your weight on the steps rather than leaning on the handles."),
        ExerciseEntity(name = "Battle Ropes", muscleGroup = "Cardio",
            description = "Grip both ends of the rope and rapidly alternate arm waves (or do simultaneous slams). Creates a highly intense full-body conditioning workout. Vary the pattern — waves, slams or circles — to target different muscles."),
        ExerciseEntity(name = "Burpee", muscleGroup = "Cardio",
            description = "From standing, drop into a squat, kick your feet back to a plank, perform a push-up, jump your feet back to your hands, and explosively jump upward with your arms overhead. A full-body high-intensity movement with no equipment needed.")
    )
}
